### PR TITLE
Zafer

### PR DESCRIPTION
**Pull request by Zafershah24**
### Issue Id you have worked upon - 
Your answer
#172
### Briefly explain your program logic - 
Your answer
We spilt the string into halves and compare both the halves whether they are equal or Not. If Equal, then it is Lapindrome else not.

### Screenshots(Attach 2 screenshots of your own input and output) - 
Attach here
Screenshot (788)
Screenshot (789)

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

- [x] I have mentioned the question as comment in my solution file.<br>
- [x] My code follows the guidelines of this project.<br>
- [x] I have performed a self-review of my own code.<br>
- [x] I have commented my code.<br>
- [x] My code gives the correct output.<br>
- [x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

- [x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@Zafershah24,
Kindly comment your code well.

**Comment by Zafershah24** [comment]
Ok Give me some time, don't close the pull request

**Comment by SarthakKeshari** [comment]
@Zafershah24,
Kindly comment your code well and update me in comments.

**Comment by Zafershah24** [comment]
I Finished Commenting the program.

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
