### PR TITLE
Climbing Stairs

### PR DESCRIPTION
**Pull request by Rajat-Jain29**
### Issue Id you have worked upon - 
#129 

### Briefly explain your program logic - 
Logic -> (Bottom Up Approach)

climbStair (n) = fibonacci (n + 1)

consider fibonacci series :- 1, 1, 2, 3, 5, 8, 13, 21, 34, ...
eg

climbStairs (2) = fibonacci (3) = 2
climbStairs (3) = fibonacci (4) = 3
climbStairs (5) = fibonacci (6) = 8
climbStairs (7) = fibonacci (8) = 21

### Screenshots(Attach 2 screenshots of your own input and output) - 

Screenshot (282)

Screenshot (283)

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by Rajat-Jain29** [comment]
Hey @SarthakKeshari . have a look at it and please merge my PR.

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
@Rajat-Jain29,
Kindly check why its showing that you have altered 2 files.

**Comment by Rajat-Jain29** [comment]
@SarthakKeshari I have not added another file. That is created by some other guy.

**Comment by SarthakKeshari** [comment]
@Rajat-Jain29,
Ok I will make the corrections

**Pull request merged**
