### PR TITLE
Solution of Shuffling Parities

### PR DESCRIPTION
**Pull request by PrasoonJain2002**
### Issue Id you have worked upon - 
#53 

### Briefly explain your program logic - 
I observed that for solving this problem if even number are taken to odd position and odd to even we can get the maximum sum. I did the same in this code.

### Screenshots(Attach 2 screenshots of sample input and output) - 

image

image

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Review by SarthakKeshari — CHANGES_REQUESTED** [review]
@PrasoonJain2002,
Kindly comment the code and add question description as comment to the solution file

**Comment by PrasoonJain2002** [comment]
@SarthakKeshari Changes have been made.

**Review by SarthakKeshari — CHANGES_REQUESTED** [review]
@PrasoonJain2002,
Kindly verify the program. Its generating errors.

**Comment by PrasoonJain2002** [comment]
@SarthakKeshari All errors have been solved.

**Comment by PrasoonJain2002** [comment]
@SarthakKeshari Pls merge this it is correct now.

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
