### PR TITLE
Solution of trapping rain water

### PR DESCRIPTION
**Pull request by pratikj697**
### Issue Id you have worked upon - 
#243 

### Briefly explain your program logic - 
image
For each element in the array, we find the maximum level of water it can trap after the rain, which is equal to the minimum of maximum height of bars on both the sides minus its own height

### Screenshots(Attach 2 screenshots of your own input and output) - 
output

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@pratikj697,
This repository only accepts C++ solutions

**Comment by SarthakKeshari** [comment]
@pratikj697,
This repository only accepts **C++** solutions

**Comment by pratikj697** [comment]
Updated solution in cpp

**Comment by SarthakKeshari** [comment]
@pratikj697,
Its Plagarized.
https://scaryrival.blogspot.com/2021/06/sbt-daily-test-10-jun-tech-mcq-code.html

Kindly don't repeat this it against the guidelines

**Review by SarthakKeshari — COMMENTED** [review]
https://scaryrival.blogspot.com/2021/06/sbt-daily-test-10-jun-tech-mcq-code.html
Plagarized

**Comment by SarthakKeshari** [comment]
@pratikj697,
If you could come up with your own answer I will appreciated that. I am removing invalid tag

**Pull request closed without merging**
