### PR TITLE
Added Gray code solution

### PR DESCRIPTION
**Pull request by diwakarsingh18277**
### Issue Id you have worked upon - 
Kindly write your answer here

### Briefly explain your program logic - 
Kindly write your answer here

### Screenshots(Attach 2 screenshots of your own input and output) - 
Attach here

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

- [] I have mentioned the question as comment in my solution file.<br>
- [] My code follows the guidelines of this project.<br>
- [] I have performed a self-review of my own code.<br>
- [] I have commented my code.<br>
- [] My code gives the correct output.<br>
- [] I confirm that I have not copied the code from anywhere. In case its found that I have copied even after successful merge then I can be banned from the repository and hacktoberfest.<br>

- [] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@diwakarsingh18277,
Kindly create an issue first and then PR. And follow the PR template and contribution guidelines.
I am not closing this PR since this was your first time. You may refer CONTRIBUTING.md and create an issue.

Kindly create an issue now and claim it.

**Comment by diwakarsingh18277** [comment]
Thanks, I have created an issue and waiting to be assigned.

**Comment by SarthakKeshari** [comment]
> Thanks, I have created an issue and waiting to be assigned.

I have recently assigned. Now you may fill the above PR with your answers to the questions asked.

**Comment by diwakarsingh18277** [comment]
Done. Commented all the code.

**Pull request merged**
