### PR TITLE
Selection Sort

### PR DESCRIPTION
**Pull request by SwarnimaShishodia**
### Issue Id you have worked upon - 
#216

### Briefly explain your program logic - 
In selection sort we need to find the index of minimum element and swap with element at ith position. Every time a element comes at correct position. Thats why we run loop second loop from i+1.

### Screenshots(Attach 2 screenshots of your own input and output) - 
Screenshot (88)

Screenshot (89)

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SwarnimaShishodia** [comment]
Hii
Please provide the feedback.
Thankyou!

**Comment by SarthakKeshari** [comment]
@SwarnimaShishodia,
Kindly use #216 instead of 216
Also comment the question that you have placed inside the solution file otherwise it will conflict with your code

**Comment by SarthakKeshari** [comment]
@SwarnimaShishodia,
May I know why the PR is closed? Its good to go

**Comment by SarthakKeshari** [comment]
@SwarnimaShishodia,
A PR can be found. Ok perfect then

**Pull request closed without merging**
