### PR TITLE
added island perimeter

### PR DESCRIPTION
**Pull request by rustzz-27**
### Issue Id you have worked upon - 
#79 

### Briefly explain your program logic - 
For every one we know that the square consists of four walls.
Now for every one found in the grid, don't add the walls which are surrounded by other blocks (i.e. 1s).
Add the ones not surrounded by any 1s (i.e. have 0 as adjacent element).

### Screenshots(Attach 2 screenshots of sample input and output) - 
image
image

### OUTPUT
image

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by rustzz-27** [comment]
Pls review my PR

**Comment by SarthakKeshari** [comment]
@rustzz-27,
Kindly attach the output that you have got.

**Comment by rustzz-27** [comment]
> @rustzz-27, Kindly attach the output that you have got also comment your code well.

I should attach the output in the PR description?

**Comment by rustzz-27** [comment]
@SarthakKeshari I have added comments to my code and also added output pic in my PR description. Pls review

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
