### PR TITLE
Create GCD-HCF.cpp

### PR DESCRIPTION
**Pull request by PrasoonJain2002**
### Briefly explain your program logic - 
Your answer

### Screenshots(Attach 2 screenshots of sample input and output) - 
Attach here

image

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@PrasoonJain2002,
1) Have you raised the issue for this PR? If yes, may I know the issue id
2) Kindly fill the above PR template and don't alter it by removing the asked questions.

**Comment by PrasoonJain2002** [comment]
Issue Id you have worked upon -
#46 

Briefly explain your program logic -
The C++ program that finds the GCD/HCF of two numbers using Recursion.

Screenshots(Attach 2 screenshots of sample input and output) -

image

Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[X] I have mentioned the question as comment in my solution file.

[X] My code follows the guidelines of this project.

[X] I have performed a self-review of my own code.

[X] I have commented my code.

[X] My code gives the correct output.

[X] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.

[X] I affirm that I strictly follow contributing guidelines and code of conduct.

**Comment by PrasoonJain2002** [comment]
> @PrasoonJain2002,
> 
> 1. Have you raised the issue for this PR? If yes, may I know the issue id
> 2. Kindly fill the above PR template and don't alter it by removing the asked questions.

I have raised the issue and filled the PR template. Please look through it.

**Comment by PrasoonJain2002** [comment]
@SarthakKeshari please review it.

**Comment by SarthakKeshari** [comment]
@PrasoonJain2002,
1) It's showing that you have made changes to CodeChef/Movie_Weekend.cpp file. Kindly revert back the changes and commit again.
2) Kindly give a bit more elaborate description for your program logic.

**Comment by PrasoonJain2002** [comment]
Issue Id you have worked upon -
#46 

Briefly explain your program logic -
The C++ program that finds the GCD/HCF of two numbers using Recursion.
In int gcd() function we have a base case condition in which if a is equal to b then we return a otherwise we go to next recursion with the help of difference of both numbers.

Screenshots(Attach 2 screenshots of sample input and output) -

image

Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[X] I have mentioned the question as comment in my solution file.

[X] My code follows the guidelines of this project.

[X] I have performed a self-review of my own code.

[X] I have commented my code.

[X] My code gives the correct output.

[X] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.

[X] I affirm that I strictly follow contributing guidelines and code of conduct.

**Comment by PrasoonJain2002** [comment]
@SarthakKeshari I think now it's okay, please review.

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
