### PR TITLE
Stock Buy and Sell to Maximize Profit

### PR DESCRIPTION
**Pull request by Rajat-Jain29**
### Issue Id you have worked upon - 
#68 

### Briefly explain your program logic - 

The logic to solve this problem is same as "max subarray problem" using Kadane's Algorithm. Since no body has mentioned this so far, I thought it's a good thing for everybody to know.

All the straight forward solution should work, but if the interviewer twists the question slightly by giving the difference array of prices, Ex: for {1, 7, 4, 11}, if he gives {0, 6, -3, 7}, you might end up being confused.

Here, the logic is to calculate the difference (maxCur += prices[i] - prices[i-1]) of the original array, and find a contiguous subarray giving maximum profit. If the difference falls below 0, reset it to zero.

*maxCur = current maximum value

*maxSoFar = maximum value found so far

<br>

### Screenshots(Attach 2 screenshots of sample input and output) -

Screenshot (279)
Screenshot (280)

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by Rajat-Jain29** [comment]
@SarthakKeshari please check once and merge this PR under Hacktoberfest :)

**Comment by SarthakKeshari** [comment]
@Rajat-Jain29,
Kindly 
1) Create issue first and after you have been assigned then create a Pull request.
2) Fill the PR template above
3) Write **complete** question as your solution file's first comment.

**Comment by Rajat-Jain29** [comment]
@SarthakKeshari Now I have created the issue and completed the PR template.

**Comment by Rajat-Jain29** [comment]
@SarthakKeshari Now I have created the issue and completed the PR template.

**Comment by Rajat-Jain29** [comment]
@SarthakKeshari Now I have created the issue and completed the PR template.

**Comment by Rajat-Jain29** [comment]
@SarthakKeshari Now I have created the issue and completed the PR template.

**Comment by Rajat-Jain29** [comment]
@SarthakKeshari Now I have created the issue and completed the PR template.

**Comment by Rajat-Jain29** [comment]
@SarthakKeshari Now I have created the issue and completed the PR template.

**Comment by SarthakKeshari** [comment]
> @Rajat-Jain29, Kindly
> 
> 1. Create issue first and after you have been assigned then create a Pull request.
> 2. Fill the PR template above
> 3. Write **complete** question as your solution file's first comment.

Kindly consider filling checklist also and affirm by the guidelines.
and also complete point 3 mentioned

**Comment by Rajat-Jain29** [comment]
@SarthakKeshari Now check. I think now it's in a proper format.

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
