### PR TITLE
Create Find k’th largest element in an array.cpp

### PR DESCRIPTION
**Pull request by Architgupta001**
### Issue Id you have worked upon - 
#167

Find k’th largest element in an array

### Briefly explain your program logic - 
A simple solution would be to use an efficient sorting algorithm to sort the array in descending order and return the element at (k - 1) 'th index. The worst-case time complexity of this approach will be 0(n.log(n)) , where n is the size of the input. We can improve the time complexity using the following methods:

### Screenshots(Attach 2 screenshots of your own input and output) - 
Input:
 
arr = [7, 4, 6, 3, 9, 1]
k = 2
 
Output:
 
The 2nd largest array element is 7

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@Architgupta001,
Kindly,
1) Add issue id
2) Mark last condition of checklist it must be agreed upon for PR to be accepted.
3) Add comment to the logical part of the code as well

**Comment by Architgupta001** [comment]
I had made the changes plz check

**Review by SarthakKeshari — APPROVED** [review]

**Comment by SarthakKeshari** [comment]
@Architgupta001,
Kindly attach the output screenshot instead of manual input/output text

**Comment by SarthakKeshari** [comment]
@Architgupta001,
Closing this PR since no response had been received

**Pull request closed without merging**
