### PR TITLE
Longest Common Subsequence

### PR DESCRIPTION
**Pull request by Ritwik009**
### Issue Id you have worked upon - 
#114 
added a question with its the solution to the leetcode folder.

### Briefly explain your program logic - 
I have used the tabulation method of dynamic programming.

### Screenshots(Attach 2 screenshots of your own input and output) - 
Attach here
Screen Shot 2021-10-02 at 10 45 53 AM
Screen Shot 2021-10-02 at 10 49 15 AM

<br>

### Checklist:
Eg - If your code follows the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as a comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented on my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@Ritwik009,
Kindly complete the above PR template by mentioning issue id and attaching the screen shots.

**Review by SarthakKeshari — CHANGES_REQUESTED** [review]
Kindly look into the files that are altered. Only 3 files seem to be useful.

**Comment by Ritwik009** [comment]
> Kindly look into the files that are altered. Only 3 files seem to be useful.

@SarthakKeshari I have made the necessary changes Sir. Kindly review it once again.

**Review by SarthakKeshari — APPROVED** [review]

**Comment by Ritwik009** [comment]
@SarthakKeshari Sir kindly merge this pull request.

**Pull request closed without merging**
