### PR TITLE
Maximum HourGlass Sum 2D Array

### PR DESCRIPTION
**Pull request by ayushjindal23**
### Issue Id you have worked upon - 
#198 

### Briefly explain your program logic - 
I created " ans "variable that will hold the lowest sum of the hourglass.
<i>ex: lowest sum will be -9 * 7 = -63 as the number goes from -9 to 9 and an hourglass is 7 elements so the count will equal -63.</i>
Then I iterated over the array and the subarray of the matrix and add up each element from subarrays for a square of 6 * 6.
Then I created a function sum to hold the total of the added elements. Check if the total sum is bigger than the ans variable. 

### Screenshots(Attach 2 screenshots of your own input and output) - 

INPUT:
image

OUTPUT:
image

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x] 

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x]  I have commented my code.<br>
[x]  My code gives the correct output.<br>
[x]  I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@ayushjindal23,
Kindly comment your code well and add question description as first comment to solution file.

**Comment by ayushjindal23** [comment]
@SarthakKeshari 
I have commented on it already.

**Comment by SarthakKeshari** [comment]
> @ayushjindal23, Kindly comment your code well and add question description as first comment to solution file.

@ayushjindal23,
Kindly add question description as first comment to solution file.

**Review by ayushjindal23 — COMMENTED** [review]
Changes are done

**Comment by ayushjindal23** [comment]
> > @ayushjindal23, Kindly comment your code well and add question description as first comment to solution file.
> 
> @ayushjindal23, Kindly add question description as first comment to solution file.

I have added question description as first comment to solution file.

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
