### PR TITLE
Movie Weekend

### PR DESCRIPTION
**Pull request by Vedika-Agrawal**
### Issue/Solution Id you have worked upon - 
#34 

### Briefly explain your program logic - 
 First, Egor wants to select a movie to watch on the weekend. But there are n numbers of movies. So he decided to watch the movie on the following criteria :
  1.  first he will choose a movie with the highest value L*R.
  2.  If there is more than one movie, then he will select with maximum rating.
  3.  still if there is a tie then he will choose with minimum index.

### Screenshots(Attach 2 screenshots of sample input and output) -

SAMPLE INPUT
2
2
1 2
2 1
4
2 1 4 1
2 4 1 4

SAMPLE OUTPUT
1
2

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by Vedika-Agrawal** [comment]
Sie please review my pr, In case of any conflict. Please let me know I will fix it.

**Comment by SarthakKeshari** [comment]
@vish-han,
Kindly fill the above details template, in order to get your PR merged.

**Review by SarthakKeshari — CHANGES_REQUESTED** [review]
Add proper comments to your code

**Comment by Vedika-Agrawal** [comment]
Okay, I will make all the necessary changes in a while.

**Review by SarthakKeshari — COMMENTED** [review]
Kindly write comments that makes your program self-explanatory for anyone who visits your code

**Comment by Vedika-Agrawal** [comment]
Done with the changes.

**Comment by SarthakKeshari** [comment]
@Vedika-Agrawal ,
Instead of MOVIEWKN you need to mention the issue id #34 generated by Github for the question you have solved. 
I have made the changes on your behalf. Just keep it in mind for further PRs. All the best

**Review by SarthakKeshari — APPROVED** [review]

**Review by SarthakKeshari — CHANGES_REQUESTED** [review]
Save your file in as .cpp. Else Everything is good to go

**Comment by SarthakKeshari** [comment]
@SarthakKeshari,
Being a beginner is a boon, be consistent. All the best. I will guide.

Happy Contributions

**Comment by SarthakKeshari** [comment]
@Vedika-Agrawal,
Being a beginner is a boon, be consistent. All the best. I will guide.
File still shows .txt kindly look into it
Happy Contributions

**Comment by Vedika-Agrawal** [comment]
Done.

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
