### PR TITLE
Created HourGlassSum.cpp file

### PR DESCRIPTION
**Pull request by iammohit07**
Provided solution to a Hackerrank Problem

###Solution to Issue number #198

### Question/ Problem Statement
Given a  2D Array of 6 x 6 :
1 1 1 0 0 0
0 1 0 0 0 0
1 1 1 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
0 0 0 0 0 0
An hourglass is a subset of values with indices falling in this pattern in this graphical representation.
There are  16 hourglasses in array . An hourglass sum is the sum of an hourglass' values. Calculate the hourglass sum for every hourglass in array, then print the maximum hourglass sum. The array will always be 6 x 6.

-9 -9 -9  1 1 1 
 0 -9  0  4 3 2
-9 -9 -9  1 2 3
 0  0  8  6 6 0
 0  0  0 -2 0 0
 0  0  1  2 4 0
The 16  hourglass sums are:

-63, -34, -9, 12, 
-10,   0, 28, 23, 
-27, -11, -2, 10, 
  9,  17, 25, 18
The highest hourglass sum is 28  from the hourglass beginning at row 1 , column 2:

0 4 3
  1
8 6 6

### Briefly explain your program logic - 
I've just created a 2-D Array and than according to question I noticed a pattern hour glass was following so I kept those indexes in array using which hour glass was forming and then simply calculated sum of the elements on those indexes.

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@iammohit07,
Kindly create an issue first and then PR. And follow the PR template and contribution guidelines.

**Comment by SarthakKeshari** [comment]
@iammohit07,
Kindly comment your code and mention issue id as #145

**Comment by SarthakKeshari** [comment]
@iammohit07,
Kindly create "Add a question" issue. I have once directed about the same in #145

**Comment by iammohit07** [comment]
Thanks for guiding me and I'm sorry for doing silly mistakes as I am beginner so that's why.

**Comment by SarthakKeshari** [comment]
@iammohit07,
Since the PR has been created before Issue assignment it needs to be closed.
Kindly follow CONTRIBUTING.md

**Pull request closed without merging**
