### PR TITLE
update permutation

### PR DESCRIPTION
**Pull request by smitaranii**
### Issue Id you have worked upon - 
#154

### Briefly explain your program logic - 
The idea is to generate all possible permutations, by repeatedly swapping the first(left-most) element with every other element in the array. Then swapping the second element(hence leftIdx + 1) with every element towards its right, and so on. This is achieved via backtracking.

### Screenshots(Attach 2 screenshots of your own input and output) - 

Screenshot (619)

Screenshot (620)
<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@smitaranii,
It shows you have altered 2 files instead of one. Kindly rectify it

**Comment by smitaranii** [comment]
okay

**Review by smitaranii — COMMENTED** [review]
Update the files accordingly

**Comment by smitaranii** [comment]
Added permutation on leetcode folder.

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
