### PR TITLE
Prison_Escape - hacktoberfest'21

### PR DESCRIPTION
**Pull request by manognyaa**
### Issue Id you have worked upon ✨ - #73 

problem link - https://www.hackerearth.com/practice/algorithms/graphs/depth-first-search/practice-problems/algorithm/prison-break-5/

### Briefly explain your program logic - 
I have used graph algorithm in this problem sir. If we want to see is there a path from one end to another end along the width.
We first convert the given data to the graph(possibly it will become disconnected graph). Consider the soldiers as the nodes and we will add an edge between two soldiers if there range of view has some intersection part or if they are just joining. Check every possible pair of point(Soldiers). 

Find distance b/w two i.e. If(x1 - x2)^2 + (y1 - y2)^2 <= 200 * 200 (100(from soldier1) + 100(from soldier2)). Then add the edge.

### Screenshots(Attach 2 screenshots of sample input and output) ✨ - 

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

Please kindly accept my pr @SarthakKeshari sir.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@manognyaa,
Kindly, 
1) Mention #73 in issue id section.
2) Initially whatever is placed in issue id section move it to the program logic section
3) Since the question is from an online platform. Kindly attach the url in the original issue as well as in the comments of the solution file.

**Comment by manognyaa** [comment]
hello sir, 
good morning !!

I have updated the files, Images folder and added the screenshots of i/o in the image folder and added that one also. Please review it sir and if any changes required pls guide me `@SarthakKeshari` sir.

**Comment by SarthakKeshari** [comment]
@manognyaa,
Don't add screenshot in the folder. Just upload it in the PR template.
Else everything is good to go.

**Comment by manognyaa** [comment]
> Good morning @manognyaa, Don't add screenshot in the folder. Just upload it in the PR template. Else everything is good to go.

Yes sir. I have added the screenshots in the pr template. kindly review it `@SarthakKeshari` sir.

**Pull request merged**
