### PR TITLE
Added Code Non-Decreasing Dilemma || codeforces

### PR DESCRIPTION
**Pull request by Aakash-Raj-2001**
### Issue Id you have worked upon - 
#233 

### Briefly explain your program logic - 
This problem is a typical application of segment tree.
We maintain three attributes for each interval:
1. The number of subarray that meet the condition (mark as ans);
2. Starting from the leftmost side, the length of the longest continuous non-decreasing subarray (mark as left_size);
3. Starting from the rightmost, the length of the longest non-decreasing subarray (mark as right_size).

### Screenshots(Attach 2 screenshots of your own input and output) - 
Input
Output

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied even after successful merge then I can be banned from the repository and hacktoberfest.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@Aakash-Raj-2001,
Kindly upload only .cpp file. I will ask for other files in case its required.

**Comment by Aakash-Raj-2001** [comment]
@SarthakKeshari I deleted the other files . Can you please check ?

**Comment by SarthakKeshari** [comment]
@Aakash-Raj-2001,
You seem to have .cpp instead of the other file

**Comment by SarthakKeshari** [comment]
@Aakash-Raj-2001,
Kindly add question description as first comment to solution file.

**Comment by Aakash-Raj-2001** [comment]
@SarthakKeshari I added question description to the solution file.Can you check please?

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
