### PR TITLE
Fixed issue #36 SemiSort1

### PR DESCRIPTION
**Pull request by aaditya9899**
### Issue/Solution Id you have worked upon - 
#36

### Briefly explain your program logic - 
I have first used sort function to sort them and then applied for loops to print them in ascending and descending order.

### Screenshots(Attach 2 screenshots of sample input and output) - 

**Sample Input-**
ad
5
1 4 2 6 3  
**output-**
1 2 6 4 3 

**Sample Input 2-**
da
6
2 1 3 5 4 8 
**output-**
8 5 4 1 2 3 

Untitled 1

Untitled
<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by aaditya9899** [comment]
@SarthakKeshari Please Review my pull request thankx

**Comment by SarthakKeshari** [comment]
@aaditya9899,
Kindly attach the ouptput screenshot and approve the coditions of the checklist in PR template(change [] to [x] to show your approval).

**Comment by aaditya9899** [comment]
Done

**Comment by SarthakKeshari** [comment]
@aaditya9899,
Just a guidance for next PRs.
In the Issue Id mention #36(this is issue id you can this as hashtag just beside your issue title) instead of question description.

I have fixed it myself for this PR.

All the best.

**Review by SarthakKeshari — APPROVED** [review]

**Comment by aaditya9899** [comment]
okay thankx 

> @aaditya9899, Just a guidance for next PRs. In the Issue Id mention #36(this is issue id you can this as hashtag just beside your issue title) instead of question description.
> 
> I have fixed it myself for this PR.
> 
> All the best.

got it. Thankx

**Comment by aaditya9899** [comment]
Hey was this hacktober included?

**Pull request merged**
