### PR TITLE
Reverse Nodes of  Linked List in K-Group code added

### PR DESCRIPTION
**Pull request by sksukruth**
Reverse Nodes of  Linked List in K-Group

### Issue Id you have worked upon - 
#265

### Briefly explain your program logic - 
1. Reverse the first sub-list of size k. While reversing keep track of the next node and previous node. Let the pointer to the next node be next and pointer to the previous node be previous. 
2. head->next = reverseKNodes(next, k) ( Recursively call for rest of the list and link the two sub-lists).
3. Return previous as previous becomes the new head of the list.

### Screenshots(Attach 2 screenshots of your own input and output) - 
Input:
Screenshot (635)

Output:
Screenshot (636)

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[x] I have mentioned the question as comment in my solution file.<br>
[x] My code follows the guidelines of this project.<br>
[x] I have performed a self-review of my own code.<br>
[x] I have commented my code.<br>
[x] My code gives the correct output.<br>
[x] I confirm that I have not copied the code from anywhere. In case its found that I have copied even after successful merge then I can be banned from the repository and hacktoberfest.<br>

[x] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by SarthakKeshari** [comment]
@sksukruth,
Kindly don't create PR unless the issue is assigned. Refer CONTRIBUTING.md for futher details.
I think this is your first PR, so I'll accept this one.

**Comment by SarthakKeshari** [comment]
@sksukruth,
Kindly check, Change the file location to the path I have directed you in the issue section

**Comment by sksukruth** [comment]
Changed the file location to the leetcode folder

**Comment by sksukruth** [comment]
Changed the file location to the leetcode folder

**Review by SarthakKeshari — APPROVED** [review]

**Pull request merged**
