### PR TITLE
Adding ATM.cpp

### PR DESCRIPTION
**Pull request by sej28**
Adding ATM problem from CodeChef

### Issue Id you have worked upon - 
Your answer

### Briefly explain your program logic - 
Your answer

### Screenshots(Attach 2 screenshots of your own input and output) - 
Attach here

<br>

### Checklist:
Eg - If your code follow the below guidelines. Kindly change [] to [x]

All the conditions should be fulfilled for considering your code for merging -

[] I have mentioned the question as comment in my solution file.<br>
[] My code follows the guidelines of this project.<br>
[] I have performed a self-review of my own code.<br>
[] I have commented my code.<br>
[] My code gives the correct output.<br>
[] I confirm that I have not copied the code from anywhere. In case its found that I have copied I can be banned from the repository.<br>

[] I affirm that I strictly follow contributing guidelines and code of conduct.

### CODE REVIEW

**Comment by aaditya9899** [comment]
assign me pls

**Comment by aaditya9899** [comment]
and also would it be part of hactoberfest

**Comment by SarthakKeshari** [comment]
@sej28,
Kindly create an issue first and then PR. And follow the PR template and contribution guidelines

**Comment by sej28** [comment]
Ohh okay, Done
Thank you

**Pull request closed without merging**
